# Generated by Django 4.0.2 on 2022-12-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_field',
            field=models.FileField(upload_to='media/uploads'),
        ),
    ]
