# Generated by Django 4.0.2 on 2022-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_field',
            field=models.FileField(upload_to='C:\\Users\\Пользователь\\Downloads'),
        ),
    ]
